apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-checkout
  namespace: argocd
spec:
  description: Project for team-checkout
  sourceRepos:
    - https://github.com/Acoolwolf96/platform-project.git
  destinations:
    - namespace: team-checkout
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
